# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3042b68019636fd15fdeed73a08335b14fea86914e9ca3abece9a537e8a3af6b2adac5cd57c6244317d82c0fa5fa42426612cf34a8e2433fb8491579743236e3

test:
  secret_key_base: 0af5be7511fde5036d6b6c2956a6879b70ac6681fa70335df44eba21050de09a1ce00cd8d3572c56f2601ae164c9a4be38aa63570b430fe9f7cb87c1e2b0070a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
